# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedchart",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Prefer not to say"),
                    ("female", "Female"),
                    ("male", "Male"),
                    ("non_binary", "Non-binary"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="savedchart",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Prefer not to say"),
                    ("unmarried", "Unmarried"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=40)),
                ("month", models.DateField()),
                ("prediction_version", models.CharField(default="v1", max_length=24)),
                ("answer_language", models.CharField(default="English", max_length=40)),
                ("computed_context", models.JSONField(blank=True, default=dict)),
                ("prediction_text", models.TextField()),
                ("model_name", models.CharField(blank=True, max_length=80)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_predictions",
                        to="charts.savedchart",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "topic"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["chart", "topic", "month", "prediction_version", "answer_language"],
                        name="unique_monthly_prediction_cache",
                    )
                ],
            },
        ),
    ]
